
import NavbarComponent from "@/components/NavbarComponent";
import SidebarComponent from "@/components/SidebarComponent";
import Image from "next/image";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body className="font-SFProDisplay">
            <div className="flex">

                <div>
                <SidebarComponent />
                </div>
            
               

                <div className="w-full ml-12">
                <NavbarComponent/>
                <Image src={"/assets/icons/image.png"} width={400} height={400} className="  pt-48 ml-80" />
            
                {/* <ListBoardComponentHeader /> */}
            
               </div>

               {children}
            </div>
            
        </body>
      </html>
    );
  }